"""
PDF report generation utilities.
Uses ReportLab to create professional PDF reports.
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import pandas as pd
from datetime import datetime
from typing import List, Dict, Optional
import os
import config


def generate_pdf_report(filename: str,
                       title: str,
                       data_tables: List[Dict],
                       summary_stats: Optional[Dict] = None,
                       charts: Optional[List[str]] = None) -> str:
    """
    Generate a comprehensive PDF report.
    
    Args:
        filename: Output filename
        title: Report title
        data_tables: List of dicts with 'title' and 'dataframe' keys
        summary_stats: Optional dictionary of summary statistics
        charts: Optional list of chart image paths to include
    
    Returns:
        str: Path to generated PDF
    """
    # Ensure reports directory exists
    os.makedirs(config.REPORTS_DIR, exist_ok=True)
    
    # Full path for output
    output_path = os.path.join(config.REPORTS_DIR, filename)
    
    # Create PDF document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18
    )
    
    # Container for document elements
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1f77b4'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    heading_style = styles['Heading2']
    normal_style = styles['Normal']
    
    # Add title
    elements.append(Paragraph(title, title_style))
    elements.append(Spacer(1, 12))
    
    # Add generation date
    date_text = f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    elements.append(Paragraph(date_text, normal_style))
    elements.append(Spacer(1, 20))
    
    # Add summary statistics if provided
    if summary_stats:
        elements.append(Paragraph("Summary Statistics", heading_style))
        elements.append(Spacer(1, 12))
        
        for key, value in summary_stats.items():
            text = f"<b>{key}:</b> {value}"
            elements.append(Paragraph(text, normal_style))
        
        elements.append(Spacer(1, 20))
    
    # Add data tables
    for table_dict in data_tables:
        table_title = table_dict.get('title', 'Data Table')
        df = table_dict.get('dataframe')
        
        if df is not None and not df.empty:
            elements.append(Paragraph(table_title, heading_style))
            elements.append(Spacer(1, 12))
            
            # Convert DataFrame to table data
            table_data = _dataframe_to_table(df)
            
            # Create table
            t = Table(table_data)
            
            # Style the table
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f77b4')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey])
            ]))
            
            elements.append(t)
            elements.append(Spacer(1, 20))
    
    # Add charts if provided
    if charts:
        elements.append(PageBreak())
        elements.append(Paragraph("Visualizations", heading_style))
        elements.append(Spacer(1, 12))
        
        for chart_path in charts:
            if os.path.exists(chart_path):
                try:
                    img = Image(chart_path, width=6*inch, height=4*inch)
                    elements.append(img)
                    elements.append(Spacer(1, 20))
                except Exception as e:
                    elements.append(Paragraph(f"Error loading chart: {str(e)}", normal_style))
    
    # Add footer
    elements.append(Spacer(1, 30))
    footer_text = "Generated by Poverty Dashboard"
    elements.append(Paragraph(footer_text, ParagraphStyle(
        'Footer',
        parent=normal_style,
        fontSize=8,
        textColor=colors.grey,
        alignment=TA_CENTER
    )))
    
    # Build PDF
    doc.build(elements)
    
    return output_path


def _dataframe_to_table(df: pd.DataFrame, max_rows: int = 50) -> List[List]:
    """
    Convert DataFrame to table data for ReportLab.
    
    Args:
        df: DataFrame to convert
        max_rows: Maximum number of rows to include
    
    Returns:
        List of lists for table data
    """
    # Limit rows if necessary
    if len(df) > max_rows:
        df = df.head(max_rows)
    
    # Round numeric columns
    df_display = df.copy()
    numeric_cols = df_display.select_dtypes(include=['float64', 'float32']).columns
    for col in numeric_cols:
        df_display[col] = df_display[col].round(2)
    
    # Convert to list of lists
    table_data = [df_display.columns.tolist()] + df_display.values.tolist()
    
    return table_data


def create_simple_report(filename: str,
                        title: str,
                        content: str) -> str:
    """
    Create a simple text-based PDF report.
    
    Args:
        filename: Output filename
        title: Report title
        content: Text content for the report
    
    Returns:
        str: Path to generated PDF
    """
    # Ensure reports directory exists
    os.makedirs(config.REPORTS_DIR, exist_ok=True)
    
    # Full path for output
    output_path = os.path.join(config.REPORTS_DIR, filename)
    
    # Create PDF document
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    
    # Container for elements
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = styles['Title']
    normal_style = styles['Normal']
    
    # Add content
    elements.append(Paragraph(title, title_style))
    elements.append(Spacer(1, 20))
    
    # Split content into paragraphs
    paragraphs = content.split('\n')
    for para in paragraphs:
        if para.strip():
            elements.append(Paragraph(para, normal_style))
            elements.append(Spacer(1, 12))
    
    # Build PDF
    doc.build(elements)
    
    return output_path


def export_dataframe_to_csv(df: pd.DataFrame, filename: str) -> str:
    """
    Export DataFrame to CSV file.
    
    Args:
        df: DataFrame to export
        filename: Output filename
    
    Returns:
        str: Path to exported file
    """
    # Ensure exports directory exists
    os.makedirs(config.EXPORTS_DIR, exist_ok=True)
    
    # Full path for output
    output_path = os.path.join(config.EXPORTS_DIR, filename)
    
    # Export to CSV
    df.to_csv(output_path, index=False)
    
    return output_path


def export_dataframe_to_excel(df: pd.DataFrame, filename: str) -> str:
    """
    Export DataFrame to Excel file.
    
    Args:
        df: DataFrame to export
        filename: Output filename
    
    Returns:
        str: Path to exported file
    """
    # Ensure exports directory exists
    os.makedirs(config.EXPORTS_DIR, exist_ok=True)
    
    # Full path for output
    output_path = os.path.join(config.EXPORTS_DIR, filename)
    
    # Export to Excel
    df.to_excel(output_path, index=False, engine='openpyxl')
    
    return output_path
